### PR TITLE
JsMinFilter: do not minify minified files

### PR DESCRIPTION
**Pull request by fprochazka**

### CODE REVIEW

**Comment by castamir** [comment]
what about "ends with `.min.js`"?

**Comment by fprochazka** [comment]
:+1:

**Comment by castamir** [comment]
Don't be so happy about it, it doesn't work at all!

**Comment by castamir** [comment]
You have to first fix Webloader itself to let this work... 

You have to fix these lines in [Compiler](https://github.com/janmarek/WebLoader/blob/c8765403d710b4ad0c7ef19aa90dba9683f3256b/WebLoader/Compiler.php#L162-L169)

**Comment by castamir** [comment]
I've stabilized master branch. As soon as you fix Webloader, send this PR again with proper tests...

**Comment by fprochazka** [comment]
Weird, it works for us....

**Comment by fprochazka** [comment]
Well, you have to register it to `fileFilters`, not `filters`. Then it will work :)

**Comment by fprochazka** [comment]
But I guess that is a BC break for you, isn't it?

**Comment by castamir** [comment]
It was, but I fixed it. It works both ways now. It shoudn't be BC break anymore...

**Comment by castamir** [comment]
Anyway, GREAT idea! My previous workaround looks so silly compared to this solution :+1: 

Thx!

**Comment by fprochazka** [comment]
:+1:

**Pull request merged**
